export type CharacterSummaryContext = {
  name: string
  role: string
  summary: string
  notes: string
  strength: number
  dexterity: number
  constitution: number
  intelligence: number
  wisdom: number
  charisma: number
}

export function canGenerateCharacterSummary(): boolean {
  return Boolean(process.env.OPENAI_API_KEY)
}

export function buildCharacterSummaryPrompt(context: CharacterSummaryContext): string {
  return [
    'Write a concise character summary in a fantasy RPG tone.',
    'Keep the result to one or two short paragraphs.',
    'Do not mention that this was generated by AI.',
    '',
    `Name: ${context.name || 'Unnamed character'}`,
    `Role: ${context.role || 'No role set'}`,
    `Existing summary: ${context.summary || 'No summary yet.'}`,
    `Notes: ${context.notes || 'No notes yet.'}`,
    `Stats: STR ${context.strength}, DEX ${context.dexterity}, CON ${context.constitution}, INT ${context.intelligence}, WIS ${context.wisdom}, CHA ${context.charisma}`,
  ].join('\n')
}

export function buildCharacterSummaryDraft(context: CharacterSummaryContext): string {
  const role = context.role || 'adventurer'
  const name = context.name || 'This character'
  const summary = context.summary.trim()
  const notes = context.notes.trim()
  const highestStat = Math.max(
    context.strength,
    context.dexterity,
    context.constitution,
    context.intelligence,
    context.wisdom,
    context.charisma
  )

  const focus =
    highestStat >= 16
      ? 'Their strengths hint at a clearly defined path.'
      : 'Their abilities are balanced enough to leave room for surprise.'

  const lines = [`${name} is a ${role} with a distinct presence.`]

  if (summary.length > 0) {
    lines.push(summary)
  }

  if (notes.length > 0) {
    lines.push(notes)
  }

  lines.push(focus)

  return lines.join(' ')
}
